import { Restaurant } from './restaurant';

export const RESTAURANTS: Restaurant[] = [
    {id: 1, name:"Name", address: "11 main", description: "burger joint", restaurantLink: "mcdonalds.com", restaurantType: "Fast Food", foodType: "American", priceRange: "Cheap", imageURL: "https://www.mcdonalds.com/content/dam/usa/logo/m_logo.png" },
    {id: 2, name:"Name", address: "12 main", description: "sushi place", restaurantLink: "", restaurantType: "Sit Down", foodType: "Japanese", priceRange: "Cheap", imageURL: "" },
    {id: 3, name:"Name", address: "13 main", description: "tea house", restaurantLink: "", restaurantType: "Sit Down", foodType: "English", priceRange: "Cheap", imageURL: "" },
    {id: 4, name:"Name", address: "14 main", description: "sandwich shop", restaurantLink: "", restaurantType: "Fast Food", foodType: "American", priceRange: "Cheap", imageURL: "" },
    {id: 5, name:"Name", address: "15 main", description: "brauhaus", restaurantLink: "", restaurantType: "Bar", foodType: "German", priceRange: "Cheap", imageURL: "" },
    {id: 6, name:"Name", address: "16 main", description: "italian place", restaurantLink: "", restaurantType: "Sit Down", foodType: "Italian", priceRange: "Cheap", imageURL: "" },
    {id: 7, name:"Name", address: "17 main", description: "ramen shop", restaurantLink: "", restaurantType: "Fast Food", foodType: "American", priceRange: "Cheap", imageURL: "" },
    {id: 8, name:"Name", address: "18 main", description: "mexican grill", restaurantLink: "", restaurantType: "Sit Down", foodType: "Mexican", priceRange: "Midrange", imageURL: "" },
    {id: 9, name:"Name", address: "19 main", description: "steakhouse", restaurantLink: "", restaurantType: "Sit Down", foodType: "American", priceRange: "Expensive", imageURL: "" },
    {id: 10, name:"The Shack on Broadway", address: "3215 Broadway N, Fargo, ND 58102", description: "Breakfast Restaurant", restaurantLink: "https://www.shackonbroadway.com/", restaurantType: "Sit Down", foodType: "American", priceRange: "Midrange", imageURL: "https://irp-cdn.multiscreensite.com/1393bf66/import/clib/shackonbroadway_com/dms3rep/multi/tablet/shack-logo-large-338x338.png" },
    {id: 11, name:"Fortune House", address: "1100 19th Ave N, Fargo, ND 58102", description: "Chinese Buffet", restaurantLink: "https://www.fortunehousefargo.net/", restaurantType: "Buffet", foodType: "Chinese", priceRange: "Cheap", imageURL: "https://www.facebook.com/251214121668617/photos/1573502146106468/" },
    {id: 12, name:"Red Pepper", address: "1105 19th Ave N, Fargo, ND 58102", description: "Taco Shop", restaurantLink: "https://www.redpepper.com/", restaurantType: "Sit Down", foodType: "Mexican", priceRange: "Cheap", imageURL: "https://www.redpepper.com/wp-content/themes/RedPepper/images/logotop.png" },
    {id: 13, name:"Mezzaluna", address: "309 Roberts St N, Fargo, ND 58102", description: "Fancy American Place", restaurantLink: "https://www.dinemezzaluna.com/", restaurantType: "Sit Down", foodType: "American", priceRange: "Expensive", imageURL: "https://www.dinemezzaluna.com/wp-content/uploads/2017/06/MezzalunaLogo.png" },
    {id: 14, name:"Würst Bier Hall", address: "630 1st Ave N, Fargo, ND 58102", description: "German Bar", restaurantLink: "https://wurstfargo.com/wurst-bier-hall-downtown-fargo/", restaurantType: "Bar", foodType: "German", priceRange: "Cheap", imageURL: "http://wurst.stewsites.com/wp-content/uploads/sites/25/2018/08/wurst-web-logo-300x79.png" },
    {id: 15, name:"The Boiler Room", address: "210 Roberts Alley, Fargo, ND 58102", description: "Bar with American Food", restaurantLink: "https://www.boilerroomfargo.com/", restaurantType: "Bar", foodType: "American", priceRange: "Midrange", imageURL: "https://static.wixstatic.com/media/d8d5b4_a2e94f3e68684668a0f22b363b51752d~mv2.png/v1/fill/w_204,h_128,al_c,q_80,usm_0.66_1.00_0.01/d8d5b4_a2e94f3e68684668a0f22b363b51752d~mv2.webp" },
    {id: 16, name:"Blackbird Woodfire", address: "206 Broadway N, Fargo, ND 58102", description: "Pizza place", restaurantLink: "http://www.blackbirdwoodfire.com/", restaurantType: "Sit Down", foodType: "American", priceRange: "Midrange", imageURL: "http://www.blackbirdwoodfire.com/wp-content/uploads/2014/04/blackbird-woodfire-logo-high-quality.png" },
    {id: 17, name:"Mango's", address: "2901 Main Ave, Fargo, ND 58103", description: "Mexican American", restaurantLink: "mangosfargo.com", restaurantType: "Sit Down", foodType: "Mexican", priceRange: "Midrange", imageURL: "http://mangosfargo.com/communities/2/000/001/516/502//images/6593217.png" },
    {id: 18, name:"Grand Junction Subs", address: "1100 19th Ave N B, Fargo, ND 58102", description: "Sub shop", restaurantLink: "https://grandjunctionsubs.com/fargo-north/", restaurantType: "Sit Down", foodType: "American", priceRange: "Cheap", imageURL: "https://1mc-kauffman.s3.amazonaws.com/uploads/omc_engine/company/logo/16845/display_GJ_20Logo.jpg" },
    {id: 19, name:"Rhombus Guys", address: "606 Main Ave, Fargo, ND 58103", description: "Pizza restaurant", restaurantLink: "https://rhombuspizza.com/", restaurantType: "Sit Down", foodType: "American", priceRange: "Midrange", imageURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR72JZWWAbnTYuFtFYC25iJ3oN56fjEBtYh5WoP6ZacG4n5mMQI"},
];

