import { Restaurant } from './restaurant';

export const RESTAURANTS: Restaurant[] = [
    {id: 1, name:"McDonald's", address: "1220 19th Ave N, Fargo, ND 58102", description: "Fast food chain, known for burgers", restaurantLink: "https://www.mcdonalds.com/us/en-us.html", restaurantType: "Fast Food", foodType: "American", priceRange: "Cheap", imageURL: "https://www.mcdonalds.com/content/dam/usa/logo/m_logo.png" },
    {id: 2, name:"Season Buffet", address: "3838 Main Ave, Fargo, ND 58103", description: "Chinese Buffet", restaurantLink: "http://seasonbuffetfargo.com/", restaurantType: "Buffet", foodType: "Chinese", priceRange: "Cheap", imageURL: "http://seasonbuffetfargo.com/communities/7/000/002/033/617//images/13283185.jpg" },
    {id: 3, name:"Pizza Ranch", address: "4480 23rd Ave S STE A, Fargo, ND 58104", description: "Pizza Buffet", restaurantLink: "https://pizzaranch.com/", restaurantType: "Buffet", foodType: "English", priceRange: "Midrange", imageURL: "https://pizzaranch.com/locations/images/header-logo.svg" },
    {id: 4, name:"Toscana", address: "202 Broadway N, Fargo, ND 58102", description: "Old World Tuscan cuisine", restaurantLink: "http://www.toscanadowntown.com/", restaurantType: "Sit Down", foodType: "Italain", priceRange: "Midrange", imageURL: "http://www.toscanadowntown.com/img/logo.png" },
    {id: 5, name:"Johnny Carino's", address: "4410, 17th Ave S, Fargo, ND 58103", description: "Classic Italian chain restaurant", restaurantLink: "https://www.carinos.com/", restaurantType: "Sit Down", foodType: "Italian", priceRange: "Midrange", imageURL: "https://www.carinos.com/asset/img/logo.png" },
    {id: 6, name:"Wasabi & Pokebowl", address: "560 2nd Ave N, Fargo, ND 58102", description: "Stylish Japanese eatery", restaurantLink: "http://www.pokebowlfargo.com/", restaurantType: "Sit Down", foodType: "Japanese", priceRange: "Midrange", imageURL: "http://www.pokebowlfargo.com/images/wasabipokebowl_dark.jpg" },
    {id: 7, name:"Osaka", address: "1111 38th St S, Fargo, ND 58103", description: "Traditional Japanese steakhouse & sushi bar", restaurantLink: "http://osakafargo.com/", restaurantType: "Sit Down", foodType: "Japanese", priceRange: "Midrange", imageURL: "http://osakafargo.com/wp-content/uploads/2014/05/osaka1-300x189.jpg" },
    {id: 8, name:"Arby's", address: "1117 38th St NW, Fargo, ND 58102", description: "Fast-food chain, known for its roast beef", restaurantLink: "https://arbys.com/", restaurantType: "Fast Food", foodType: "American", priceRange: "Cheap", imageURL: "https://arbys.com/images/arbys_110x85.png" },
    {id: 9, name:"Wendy's", address: "3111 13th Ave SW, Fargo, ND 58103", description: "Fast food chain for burgers", restaurantLink: "https://www.wendys.com/", restaurantType: "Fast Food", foodType: "American", priceRange: "Cheap", imageURL: "https://www.wendys.com/themes/custom/wendys_main/logo.svg" },
    {id: 10, name:"The Shack on Broadway", address: "3215 Broadway N, Fargo, ND 58102", description: "Breakfast Restaurant", restaurantLink: "https://www.shackonbroadway.com/", restaurantType: "Sit Down", foodType: "American", priceRange: "Cheap", imageURL: "https://irp-cdn.multiscreensite.com/1393bf66/import/clib/shackonbroadway_com/dms3rep/multi/tablet/shack-logo-large-338x338.png" },
    {id: 11, name:"Fortune House", address: "1100 19th Ave N, Fargo, ND 58102", description: "Chinese Buffet", restaurantLink: "https://www.fortunehousefargo.net/", restaurantType: "Buffet", foodType: "Chinese", priceRange: "Cheap", imageURL: "http://a.mktgcdn.com/p/wHx4FGDE-4EKkVySgg5WfxwdB_5TZddvq2Bmw0cW4w0/500x500.png" },
    {id: 12, name:"Red Pepper", address: "1105 19th Ave N, Fargo, ND 58102", description: "Taco Shop", restaurantLink: "https://www.redpepper.com/", restaurantType: "Sit Down", foodType: "Mexican", priceRange: "Cheap", imageURL: "https://www.redpepper.com/wp-content/themes/RedPepper/images/logotop.png" },
    {id: 13, name:"Mezzaluna", address: "309 Roberts St N, Fargo, ND 58102", description: "Fancy American Restaurant", restaurantLink: "https://www.dinemezzaluna.com/", restaurantType: "Sit Down", foodType: "American", priceRange: "Expensive", imageURL: "https://roadtips.typepad.com/.a/6a00d8341cad8253ef01bb09b6ae05970d-350wi" },
    {id: 14, name:"Würst Bier Hall", address: "630 1st Ave N, Fargo, ND 58102", description: "German Bar", restaurantLink: "https://wurstfargo.com/wurst-bier-hall-downtown-fargo/", restaurantType: "Bar", foodType: "German", priceRange: "Cheap", imageURL: "http://wurst.stewsites.com/wp-content/uploads/sites/25/2018/08/wurst-web-logo-300x79.png" },
    {id: 15, name:"The Boiler Room", address: "210 Roberts Alley, Fargo, ND 58102", description: "Bar with American Food", restaurantLink: "https://www.boilerroomfargo.com/", restaurantType: "Bar", foodType: "American", priceRange: "Midrange", imageURL: "https://static.wixstatic.com/media/d8d5b4_a2e94f3e68684668a0f22b363b51752d~mv2.png/v1/fill/w_204,h_128,al_c,q_80,usm_0.66_1.00_0.01/d8d5b4_a2e94f3e68684668a0f22b363b51752d~mv2.webp" },
    {id: 16, name:"Blackbird Woodfire", address: "206 Broadway N, Fargo, ND 58102", description: "Pizza place", restaurantLink: "http://www.blackbirdwoodfire.com/", restaurantType: "Sit Down", foodType: "American", priceRange: "Midrange", imageURL: "http://www.blackbirdwoodfire.com/wp-content/uploads/2014/04/blackbird-woodfire-logo-high-quality.png" },
    {id: 17, name:"Mango's", address: "2901 Main Ave, Fargo, ND 58103", description: "Mexican American", restaurantLink: "mangosfargo.com", restaurantType: "Sit Down", foodType: "Mexican", priceRange: "Cheap", imageURL: "http://mangosfargo.com/communities/2/000/001/516/502//images/6593217.png" },
    {id: 18, name:"Grand Junction Subs", address: "1100 19th Ave N B, Fargo, ND 58102", description: "Sub shop", restaurantLink: "https://grandjunctionsubs.com/fargo-north/", restaurantType: "Sit Down", foodType: "American", priceRange: "Cheap", imageURL: "https://1mc-kauffman.s3.amazonaws.com/uploads/omc_engine/company/logo/16845/display_GJ_20Logo.jpg" },
    {id: 19, name:"Rhombus Guys", address: "606 Main Ave, Fargo, ND 58103", description: "Pizza restaurant", restaurantLink: "https://rhombuspizza.com/", restaurantType: "Sit Down", foodType: "American", priceRange: "Midrange", imageURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR72JZWWAbnTYuFtFYC25iJ3oN56fjEBtYh5WoP6ZacG4n5mMQI"},
    {id: 20, name:"The Toasted Frog", address: "305 Broadway N, Fargo, ND 58102", description: "Eclectic restaurant", restaurantLink: "https://www.toastedfrog.com/", restaurantType: "Sit Down", foodType: "American", priceRange: "Expensive", imageURL: "https://www.toastedfrog.com/wp-content/themes/toastedfrog/images/logo.png"},

];

